package com.github.onlynight.sqlitejt.sqlitejt;

/**
 * contains some sqlite keywords and command
 * 
 * @author onlynight
 * 
 */
public interface SQLiteUtils {

	String SQLITE_DATA_TYPE_TEXT = "TEXT";
	String SQLITE_DATA_TYPE_INTEGER = "INTEGER";
	String SQLITE_DATA_TYPE_SHORT = "INT";
	String SQLITE_DATA_TYPE_LONG = "BIGINT";
	String SQLITE_DATA_TYPE_FLOAT = "FLOAT";
	String SQLITE_DATA_TYPE_DOUBLE = "DOUBLE";
	String SQLITE_DATE_TYPE_VAECHAR = "VARCHAR";
	String SQLITE_DATA_TYPE_BOOLEAN = "BOOLEAN";

	String SQLITE_CONSTRAINT_PRIMARY_KEY = "PRIMARY KEY";
	String SQLITE_CONSTRAINT_FOREIGN_KEY = "FOREIGN KEY";
	String SQLITE_CONSTRAINT_NOT_NULL = "NOT NULL";
	String SQLITE_CONSTRAINT_UNIQUE = "UNIQUE";
	String SQLITE_CONSTRAINT_DEFAULT = "DEFAULT";
	String SQLITE_CONSTRAINT_CHECK = "CHECK";

	String SQLITE_KEYWORD_CREATE = "CREATE";
	String SQLITE_KEYWORD_UPDATE = "UPDATE";
	String SQLITE_KEYWORD_SELECT = "SELECT";
	String SQLITE_KEYWORD_DELETE = "DELETE";
	String SQLITE_KEYWORD_INSERT = "INSERT";
	String SQLITE_KEYWORD_TABLE = "TABLE";
	String SQLITE_KEYWORD_FROM = "FROM";
	String SQLITE_KEYWORD_WHERE = "WHERE";
	String SQLITE_KEYWORD_AUTOINCREASEMENT = "AUTOINCREMENT";
	String SQLITE_KEYWORD_REFERENCES = "REFERENCES";
	String SQLITE_KEYWORD_VALUES = "VALUES";
	String SQLITE_KEYWORD_SET = "SET";

	String SQLITE_CMD_CREATE_TABLE = SQLITE_KEYWORD_CREATE
			+ " " + SQLITE_KEYWORD_TABLE;
	String SQLITE_CMD_DROP_TABLE_IF_EXIST = "DROP TABLE IF EXISTS";
	String SQLITE_CMD_INSERT = SQLITE_KEYWORD_INSERT
			+ " INTO";
	String ON_DELETE_CASCADE = "ON DELETE CASCADE";
	String ON_UPDATE_CASCADE = "ON UPDATE CASCADE";
}
